################################################### -
## Title: Export tables to Word for PI review
## Author: Ray Pomponio
## Email: pomponiord@upmc.edu
## Project: AGE Immunocompromised
## Date Created: 2026-04-20
## Note: Code written with assistance from Claude (Anthropic);
##       all analytical decisions made by the author
################################################### -

library(officer)
library(flextable)

# run the analysis script first to produce tab.demo and tab.outcomes
source("prelim.R")

# ── Export helpers ────────────────────────────────────────────────────────────

# convert a gtsummary table to a flextable with clean formatting
to.ft <- function(tbl, title) {
  tbl |>
    as_flex_table() |>
    set_caption(caption=title) |>
    font(fontname="Arial", part="all") |>
    fontsize(size=10, part="all") |>
    fontsize(size=11, part="header") |>
    autofit()
}

# ── Build Word document ───────────────────────────────────────────────────────

ft.demo <- to.ft(
  tab.demo,
  title="Table 1. Demographic and baseline characteristics by immunocompromised status")

ft.outcomes <- to.ft(
  tab.outcomes,
  title="Table 2. Clinical outcomes by immunocompromised status")

doc <- read_docx() |>
  # table 1
  body_add_par("", style="Normal") |>
  body_add_flextable(ft.demo) |>
  # page break between tables
  body_add_break() |>
  # table 2
  body_add_par("", style="Normal") |>
  body_add_flextable(ft.outcomes)

print(doc, target="Immunocomp - Prelim Tables - Generated by Ray.docx")
cat("Saved: prelim_immunocomp_tables.docx\n")
